### PR TITLE
Major structure update [WIP]

### PR DESCRIPTION
**Pull request by owenvoke**
- Changed to OOP
- Changed to be PSR-4 compliant
- Changed to be PSR-2 compliant
- Updated various functions
- Changed functions to reside inside classes to reduce code duplication

This technically isn't completely finished, but it's working fine.

### CODE REVIEW

**Comment by owenvoke** [comment]
Note that it now uses the `public/` folder as the web root. :)

**Comment by owenvoke** [comment]
Also, it's going to need a new constant of some sort for URLs, which I'll add when I get home.

**Comment by uziiuzair** [comment]
I had a look at the code and I agree we would need a new constant. I'll add it now.

**Comment by owenvoke** [comment]
Add it to the Config class which is probably best. :)

**Comment by uziiuzair** [comment]
Done! :) Called it PIPES_PUBLIC

**Pull request merged**
